apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: net-app
  template:
    metadata:
      labels:
        app: net-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
              name: nginx
        - name: multitool
          image: wbitt/network-multitool:latest
          env:
            - name: HTTP_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: multitool
