apiVersion: v1
kind: Service
metadata:
  name: net-app-nodeport
spec:
  selector:
    app: net-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081
